name: webp_converter
description: Application to convert images to WebP images
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  equatable: ^2.0.7
  file_picker: ^8.1.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_rust_bridge: 2.7.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  path_provider: ^2.1.5
  rust_lib_webp_converter:
    path: rust_builder
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true